// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookRunEconomy = { decisionType: string | null, commandClass: string | null, bypassReason: string | null, exactOutputReason: string | null, originalBytes: bigint | null, replacementBytes: bigint | null, modelVisibleBytes: bigint | null, outputOriginalBytes: bigint | null, outputModelVisibleBytes: bigint | null, tokenBudget: bigint | null, originalTokenCount: bigint | null, estimatedSavedTokens: bigint | null, artifactRefs?: Array<string>, };
